### ISSUE TITLE
Problems running samplefilter.go

### ISSUE THREAD

**Issue by Freeaqingme** [leonrbaker/gomilter#2]
Hi,

I tried to run the samplefilter.go file. Initially it will give:
  `./main.go:46: undefined: gomilter.AddHdrs`

Replacing:
`mymilter.Flags = gomilter.AddHdrs|gomilter.AddRcpt`
by:
`mymilter.Flags = gomilter.ADDHDRS|gomilter.ADDRCPT`

gets rid of the error, but running it results in:

```

panic: No socket name. Set MilterRaw.Socket

goroutine 1 [running]:
github.com/Freeaqingme/gomilter.Run(0x7fd100de89c8, 0xc20803c9f0, 0x0)
    /home/dolf/Projects/ClueGetter/src/github.com/Freeaqingme/gomilter/gomilter.go:746 +0x144e
main.main()
    /home/dolf/Projects/ClueGetter/src/cluegetter/main.go:49 +0x90

goroutine 2 [runnable]:
runtime.forcegchelper()
    /usr/lib/go/src/runtime/proc.go:90
runtime.goexit()
    /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
    /usr/lib/go/src/runtime/mgc0.go:82
runtime.goexit()
    /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
    /usr/lib/go/src/runtime/malloc.go:712
runtime.goexit()
    /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
```

**Comment by leonrbaker** [comment]
Hi, I fixed samplefilter.go. It wasn't setting the Socket field in the milter struct.
